### ISSUE TITLE
Hystrix Metrics Registry?

### ISSUE THREAD

**Issue by pparth** [Netflix/spectator#238]
Hello,

Is there a Hystrix Metrics Registry integration? In our Services, we use both Dropwizard and Hystrix Metrics. I find it hard to believe that Netflix is not publishing Hystrix Metrics to Atlas, internally.

**Comment by brharrington** [comment]
Hystrix data gets published into servo. There is a servo binding as part of the Hystrix project:

https://github.com/Netflix/Hystrix/tree/master/hystrix-contrib/hystrix-servo-metrics-publisher

Internally, it is a bit messier than that. Before Hystrix was open sourced it was an internal library called dependency command and was reporting data into Atlas. There is quite a bit of tooling that consumes that data from Atlas and so there is a custom metrics publisher similar to the Hystrix servo plugin that is often used internally to preserve the legacy naming.

**Comment by pparth** [comment]
Well, we have chosen to go down the Spectator path, following the suggestions about being the new module to eventually replace Servo in many features. But now, i can see that you are telling people to go for Servo for Hystrix and Dropwizard Timers publishing. So, we are confused...

**Comment by brharrington** [comment]
@pparth sorry about the confusion, I'll try to clarify.

I think the confusion is between the API that most of the user code is written against and the bindings used to report it somewhere.

Most user code will be instrumented using either the API provided by servo-core or spectator-api. Internally we have a large amount of code using servo-core developed over many years. There are quite a few things in servo that can be quite confusing and originally spectator was just a thin wrapper to provide a simpler interface and allow pluggable registries so I could experiment. So where we are now looks something like:

![metrics_stack_now](https://cloud.githubusercontent.com/assets/1289028/11002592/9b2896aa-8462-11e5-8610-f621289e96b0.png)

Legend:

![metrics_stack_legend](https://cloud.githubusercontent.com/assets/1289028/11002598/a339b324-8462-11e5-9810-328990ca11b6.png)

What we are planning to do in the future is to swap so code written agains the servo api will use a binding to forward into spectator. Then spectator bindings for various tools will be used and the servo classes  will not be needed unless there are libraries written to those apis. That said we have quite a few backwards compatibility constraints so we can make this transition work internally without too much burden on internal teams.

However, for external users that don't have all the legacy baggage to worry about I would expect all the main parts to be in place sometime in Q1 for just using spectator independent of servo. The caveat being some of the other libraries if there are strong dependencies on the format of data produced we may have to be careful about updating them. For hystrix specifically we can provide a spectator binding and so you could opt into it. I created #240 to track that.

Does this make sense?

**Comment by pparth** [comment]
Got it. We currently use Dropwizard Metrics and Hystrix Metrics, so a hystrix-spectator-metrics-publisher should do the trick for us.
Assuming that, from the hystrix side, this is pluggable and easy to implement as a hystrix publisher, is the Spectator part straight-forward too or lacking proper interfaces? We could help with implementing it if it is not too much hassle.
