### ISSUE TITLE
DefaultCounter for a rate?

### ISSUE THREAD

**Issue by pparth** [Netflix/spectator#280]
Hello,

In the doc, it is mentioned that we can use a Counter to measure a rate e.g. a service's incoming http request rate. I do not understand how a simple counter can provide a rate, for which we need a sampling of measurements (last 1min, 5min, 15min, mean etc.) and a unit of time e.g. rqs/sec.

**Comment by brharrington** [comment]
Counters are typically used for measuring a rate and reporting that to other systems. The DefaultRegistry just maintains a count and is used most frequently [for testing](https://github.com/Netflix/spectator/wiki/Testing). With test cases I have found it more useful to just know how many times increment is called because what I'm usually trying to verify is that a counter/timer is updated as expected based on some activity on the interface.

For actual use when running an application, this is accomplished by using either the servo or metrics3 registry implementations. See this repo for some examples of using these:

https://github.com/brharrington/spectator-examples

I'll think about how to make this more clear in the sections that introduce Counter, Timer, etc. If you have a suggestion, then please let me know. 

As a side note we are discussing moving the docs from github wiki to under the main repo and then publish as a site. The main benefit is to allow PRs for docs and get some simple search for the docs.

**Comment by pparth** [comment]
What happens with adding tags and dimensionality then? We do maintain a large number of metrics3 metrics, and we manage to add what we call "static" dimensions to them when we convert them to Spectator Gauges and before we report them to Atlas. "Static" dimensions for us, are the ones that do not change their value during the lifetime of the Service instance, e.g. IP address, service name, application name, AWS instance id etc. But how can we do "runtime" dimensions then, that is dimensions that change their value based on the context, e.g. the request url, the request user agent etc if we stick to the metrics3 registry?

**Comment by brharrington** [comment]
I think the crux of the question is static vs dynamic dimensions. We use the servo registry to report to Atlas and static dimensions are configured as part of the observer ([example](https://github.com/brharrington/spectator-examples/blob/master/servo/src/main/java/com/netflix/spectator/example/servo/Main.java#L67)). Runtime dimensions would be done using the tagging on the spectator ids ([simple server example](https://github.com/brharrington/spectator-examples/blob/master/server/src/main/java/com/netflix/spectator/example/Server.java#L71)).

> We do maintain a large number of metrics3 metrics, and we manage to add what we call "static" dimensions to them when we convert them to Spectator Gauges and before we report them to Atlas.

Not sure I'm following that correctly. When using the [Metrics3 Registry](https://github.com/Netflix/spectator/wiki/Metrics3-Registry) spectator data will get mapped and registered with metrics3. It doesn't do a conversion the other way back into spectator. I typically use this for simple debugging use cases as metrics3 provides a nice JMX view of data.

However, the naming conventions are quite a bit different. Spectator is meant for reporting to something with a [dimensional data model](https://github.com/Netflix/atlas/wiki/Stack-Language#data-model) where metrics3 follows a hierarchical naming model like that used with Graphite. So the metrics3 registry will map a spectator Id to a hierarchical name ([name mapping](https://github.com/Netflix/spectator/blob/master/spectator-reg-metrics3/src/main/java/com/netflix/spectator/metrics3/NameUtils.java)). So runtime dimensions should work fine, though they will never expire with the metrics 3 registry.

In general with dynamic dimensions you need to be diligent with the number of distinct combinations and make sure to be reasonable with the values. For example, for the server you wouldn't want to use values that can come directly from the user without [sanitizing first](https://github.com/brharrington/spectator-examples/blob/master/server/src/main/java/com/netflix/spectator/example/Server.java#L114).

**Comment by pparth** [comment]
Sorry for the confusion. We do not go Spectator --> Metrics 3, but the opposite. We maintain a lot of Dropwizard Metrics per Service instance, and we want to publish them to Atlas, along with "static" dimensions. What we do is that we convert the Dropwizard Metrics to Spectator Gauges, we use the Id to   attach the "static" dimensions to these Spectator Gauges and then publish them to Atlas. so, this way, we overcome the issues we have with Graphite and the hierarchical naming convention.

**Comment by pparth** [comment]
so, when we push a Spectator DefaultCounter to Atlas, Atlas will read the dstype and do its magic and convert the ever increasing Counter to a Rate per second?

**Comment by brharrington** [comment]
If `atlas.dstype=counter`, then yes.

**Comment by pparth** [comment]
Now i get it! Thanks!
