### ISSUE TITLE
Documentation on gauges misleading

### ISSUE THREAD

**Issue by jhspaybar** [Netflix/spectator#292]
I'm attempting to add a gauge to a class which contains a Guava loading cache, and it's not clear to me how I would do this without using reflection or going through a deprecated method.  The documentation has led me to a number of options including:

`
registry.gauge("cacheSize", this, (arg) -> arg.cache.size());
`
`
registry.gauge("cacheSize", cache, LoadingCache::size);
`
and 
`
registry.methodValue("cacheSize", cache, "size");
`
The first two are using the deprecated ValueFunction methods rather than the ToDoubleFunction methods, the last uses reflection and isn't needed and makes things less safe in general.  How should I be logging my cache size?

**Comment by brharrington** [comment]
You can do it with a cast:

```java
registry.gauge("cacheSize", cache, (ToDoubleFunction<LoadingCache>) LoadingCache::size);
```

In general I think it was a mistake to have overloads with lambda, but I don't know of a good option to clean it up without breaking binary compatibility. We have been debating either deprecating the ToDoubleFunction variant as well and using a different method name or removing the deprecation of ValueFunction. 

So I know it is a pain point, just not sure the best option forward yet.

**Comment by brharrington** [comment]
Discussing this with @dmuino  and looking at depotsearch results for internal usage, we are going to go ahead and remove `ValueFunction` and the overloads that support it. It isn't expected to create much of a headache internally, but is a backwards incompatible change.
