### ISSUE TITLE
[Question] How bucket works and what it's use cases?

### ISSUE THREAD

**Issue by kennedyoliveira** [Netflix/spectator#299]
Hello everyone!

Maybe i'm asking a noob question but i see this Bucket class variation like BucketCounter, BucketDistributionSummary etc, how it works, what it's advantages and use cases?

I looked at documentation and didn't found anything related to it, so i'm curious to understand it.

Thank you

**Comment by brharrington** [comment]
There is a bit of a description in this ticket:

https://github.com/Netflix/servo/issues/321#issuecomment-101115722

For usage with spectator, you would typically use a known SLA and then use one of the bucket functions. For example, suppose the SLA is 99%tile under 1 second, then you would do something like:

```java
BucketFunction f = BucketFunctions.latency(1, TimeUnit.SECONDS)
Timer t = BucketTimer.get(registry, registry.createId("http.requestLatency"), f);
```

Then you can use it like a regular timer.

**Comment by kennedyoliveira** [comment]
@brharrington, thank you, i'll read better the comments there, didn't know this feature was at first in servo, i'm felling very asleep now haha and 'll check again by tomorrow to make sure i understand your explanations there, as you pointed in the main downside of buckets

> Not as common so it isn't how most people are used to thinking about the problem.

Thats my case haha, anyway, thank you again for your help

**Comment by kennedyoliveira** [comment]
@brharrington, sorry, i forgot to leave a feedback, i understood what you explained and how to use it, it's very helpful, thank you!
