### ISSUE TITLE
support for counter pattern with time since last update

### ISSUE THREAD

**Issue by brharrington** [Netflix/spectator#369]
A pattern that is sometimes useful internally is a counter that in addition to the count tracks the time since the last update. This is used in some circumstances where there may be low activity for a period of time and there is a desire to alert on longer gaps.

Counter would have two stats:

* `count`: number of events per second
* `interval`: represents the time since the last increment, similar to `duration` for long task timers

/cc @dmuino @ken-chu

**Comment by pparth** [comment]
+1. 
Will it be available under the Atlas registry classes?

**Comment by brharrington** [comment]
It would be a pattern using the core types, so it should work with all registries.

**Comment by pparth** [comment]
Got it. Cool.
