### ISSUE TITLE
Unable to access /spectator/metrics endpoint

### ISSUE THREAD

**Issue by kk-manh** [Netflix/spectator#390]
Hi,
I have set the property spectator.webEndpoint.enabled=true in my application.properties. But I still cant access the /spectator/metrics endpoint and I dont see it being mapped during my Spring boot application startup.

The class com.netflix.spectator.controllers.MetricsController should have registered the endpoint.

**Comment by brharrington** [comment]
@ewiseblatt can probably provide better advice. I'm not that familiar with spring.

**Comment by ewiseblatt** [comment]
Do you have spring configured to load the controller? It wont do that by default.

**Comment by ewiseblatt** [comment]
If this helps, this is where we use it in spinnaker
https://github.com/spinnaker/kork/blob/14199e0557966e8a59d3ee614de0d8e7aaf5daa8/kork-core/src/main/java/com/netflix/spinnaker/kork/metrics/SpectatorConfiguration.java

The actual spring plumbing might be burried in other levels of indirection within the build and gradle dependencies. Hopefully that gives you enough of a thread to pull on.
