### ISSUE TITLE
Has use jdk7 demo?

### ISSUE THREAD

**Issue by carvendy** [Netflix/spectator#458]
Now,My many application  run by jdk7, it's difficult to change jdk 8?I need some help.

**Comment by brharrington** [comment]
The last version that supported java 7 was [0.27.0](https://github.com/Netflix/spectator/releases/tag/v0.27.0). The usage was still pretty similar to current versions. If there are specific questions I'm happy to try and answer them. For our use-cases we moved off of java 7 about two years ago, so I'm afraid I don't have any examples or environment using that version.
