### ISSUE TITLE
Deserialisation of measurements back into an Atlas Registry

### ISSUE THREAD

**Issue by pparth** [Netflix/spectator#514]
The Atlas Registry supports the serialisation of measurements into a publishPayload to be sent to Atlas. However, it does not support the de-serialisation of a publish payload to be loaded back into a new Atlas Registry. What we want to do is to send the serialised form of metric data to a data stream, consume them in a special Service that maintains its own Atlas Registry for all services, and perform various operations on it. How can we accomplish that?

**Comment by brharrington** [comment]
I haven't thought about trying to do that. Off the top of my head I'm not sure how it would reconstruct the types from the individual measurements. For example, the registry will have a single timer, but that is a composite type that will result is four measurements. So somehow it would have to reconstruct that these measurements were part of a timer and then update the state fields to based on the measurements.

This could be related to #432. In that what we were thinking is having a registry that would just forward the updates, e.g. incremented counter X by V, to another service that would maintain the state. Our use-case was something like an AWS Lambda that would be short lived so we could not rely on the registry to keep state over time. In this case it might work for what you are wanting as well. The other services would run a stateless registry that forwards to your aggregation service running atlas registry and just applies the updates.

Out of curiosity, what sort of operations are you wanting to perform?

**Comment by pparth** [comment]
Yes, this is what we want to do too: publish the measurements from all the service instances to a data stream setup and having a cluster of instances of a special service reading the measurements from the data stream, load it back into memory and do various jobs like: executing alerting expressions on per service aggregated data, perform aggregations, filtering of tags and consolidation through LWC and publishing to different retention clusters etc.

**Comment by pparth** [comment]
Do you find this to be a valid approach?

**Comment by brharrington** [comment]
Overall it makes sense.

**Comment by pparth** [comment]
So, do you think that you can be interested in providing such deserialisation support? Or at least let us know if this is even feasible?

**Comment by brharrington** [comment]
I would probably go about it with a separate registry implementation to capture the events and forward to a service that maintains the AtlasRegistry. I added some initial thoughts in https://github.com/Netflix/spectator/issues/432#issuecomment-361290271. There are several options to think about, let me know how you think the tradeoffs might impact what you are trying to accomplish.

**Comment by pparth** [comment]
Thanks. Closing this issue. I will comment in the other one.
