### ISSUE TITLE
[Discussion] Prometheus

### ISSUE THREAD

**Issue by kennedyoliveira** [Netflix/spectator#516]
Hello,

we currently use spectator in production backed by Metrics and pushing metrics to a graphite cluster, but we are trying Prometheus now and looking around i didn't found a integration with Spectator. 

I would like to know if is there something like it, to expose metrics in the Prometheus format and to push it to Pushgateway, if there isn't i'm probably going to implement it, would you be interested this feature, like opening a PR?  or i could implement in a separated project and it be linked here as a integration.

Thanks.

**Comment by brharrington** [comment]
There isn't anything like that currently. PR welcome.

**Comment by brharrington** [comment]
PRs welcome, but nothing being actively tracked here so I'm going to go ahead and close.
