### ISSUE TITLE
is spectator support max logic, like MaxGauge in servo?

### ISSUE THREAD

**Issue by wujimin** [Netflix/spectator#520]
i search in spectator code and google it, but did not get information about this.

**Comment by brharrington** [comment]
There is as an internal detail of some registries, but not exposed as part of the public api. Typically users use a [distribution summary](http://netflix.github.io/spectator/en/latest/intro/dist-summary/) instead which provides a max stat for most registry implementations.

**Comment by wujimin** [comment]
i read source code of DefaultDistributionSummary, but it only do some increment operation.

so that means default not support max logic
but if we choose other registry to create other distribution summary, like "ServoDistributionSummary",  then can get max value?

**Comment by brharrington** [comment]
The default registry is mostly only used in test cases. The ServoRegistry and AtlasRegistry would provide a max stat for distribution summaries.

**Comment by wujimin** [comment]
got it. thanks.
