### ISSUE TITLE
support polled meter that allows multiple values to be updated

### ISSUE THREAD

**Issue by brharrington** [Netflix/spectator#522]
Right now the PolledMeter helper provides a hook for a single gauge. In some cases there may be good reasons to support a single call to the lambda that can then be used to update many other meters.

/cc @corindwyer

**Comment by mirak94** [comment]
Is there any guidance for how to contribute on this? (If you accept?)

**Comment by brharrington** [comment]
Contributions are welcome, see the [general contribution guidelines](https://github.com/Netflix/spectator/blob/master/CONTRIBUTING.md) for more details.

If you mean specific to this issue, looking though [PolledMeter](https://github.com/Netflix/spectator/blob/master/spectator-api/src/main/java/com/netflix/spectator/api/patterns/PolledMeter.java) is probably a good place to start. I'm not sure exactly what it would look like, probably specifying a function that takes the object and the registry and then the user figures out what to update.

**Comment by brharrington** [comment]
Can be done with a dedicated thread pool or there is now a helper to schedule simple tasks using the shared pool for gauges (#957).
