### ISSUE TITLE
Add support for java.util.function.Supplier timing to Timer

### ISSUE THREAD

**Issue by osi** [Netflix/spectator#566]
Similar to how the `Callable` helper works, add one for `Supplier`. It is beneficial because `Callable` throws a checked exception which limits where it can be used (eg, in a `Stream` pipeline)

**Comment by brharrington** [comment]
I'm open to it, but need to think of an appropriate name. One thing we currently regret is having two overloads for record, one that takes Runnable and one that takes Callable. Overloads and lambda don't work that well together.

Not sure when I'll get to it, feel free to submit a PR.

**Comment by osi** [comment]
no worries - i'll keep all that in mind!
