### ISSUE TITLE
ArrayTagSet#addAll(Map<String, String> ts) can throw ArrayOutOfBoundsException

### ISSUE THREAD

**Issue by elandau** [Netflix/spectator#733]
Using version 0.92.1 I ran into an ArrayIndexOutOfBoundsException while adding tags stored in a ConcurrentMap.  This can happen if an item is added after the array is created but before the map is iterated on.  

```
java.lang.ArrayIndexOutOfBoundsException: 1
        at com.netflix.spectator.api.ArrayTagSet.addAll(ArrayTagSet.java:169)
        at com.netflix.spectator.api.DefaultId.withTags(DefaultId.java:71)
        at com.netflix.spectator.api.DefaultId.withTags(DefaultId.java:26)
 ```

**Comment by brharrington** [comment]
While the exception could be avoided, I'm not sure that is the best option. I would argue if you are hitting this error it indicates a correctness bug in creating the id as there is no way to know that the correct tags are added. Avoiding the exception would just make it a silent failure that could be quite difficult to debug. Even as it is it seems quite likely you could also have silent failures where a given tag is overwritten from another context and some data ends up tagged incorrectly.

**Comment by elandau** [comment]
While I see your point regarding correctness, in my specific use case using a ConcurrencyMap meant that I've chosen to avoid lock contention and am willing to accept rare situations where a tag may be dropped.  My expectation for withTags was that it would take a current snapshot and never fail.  With that said, I can concede that this may not be true in the general case.  This could potentially be addressed either via documentation, special casing ConcurrentMap somehow, or even identifying the situation and maybe throw a more meaning exception, such as a ConcurrentModificationException.
